ktor:
    application:
        modules:
            - com.al.ApplicationKt.module
    deployment:
        port: 8080
    development: true
    security:
        jwt:
            secret: ${JWT_SECRET}
            issuer: "al"
            audience: "taskqilr"
            realm: "taskqilr"